#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo 'No configuration provided'
    exit 1
fi

declare -A ENVS
ENVS[kjanosz.com]="nixos kjanosz.com"
ENVS[kj.laptop]="nixos laptop kj.laptop"
ENVS[kjw.laptop]="nixos laptop kjw.laptop"

BASE=`dirname "$(readlink -f "$0")"`
CONFIG=$1
ENV="${2:-''}"

GREEN='\033[0;32m'
NC='\033[0m' # No Color

link_files() {
  find "$1" -type f -printf '%P\n' | while IFS= read -rd $'\n' file; do
    path="$1/$file"
    dir=`dirname "$path"`

    mkdir -p $dir
    if [ ${file: -4} == ".gpg" ]; then # treat it as an encrypted file
      file_dir=`dirname "$file"`
      file_name=`basename "$file" .gpg`
      echo "Decrypting $file"
      gpg --no-verbose --quiet --batch --yes --output "$HOME/$file_dir/$file_name" --decrypt "$path"
    else
      echo "Linking $file"
      ln -sf "$path" "$HOME/$file"
    fi
  done
}

echo -e "${GREEN}Linking default files...${NC}"
link_files "$BASE/default/$CONFIG"

IFS=', ' read -r -a es <<< "${ENVS[$ENV]}"
for e in "${es[@]}"
do
  if [ -d "$BASE/custom/$e/$CONFIG" ]; then
    echo 
    echo -e "${GREEN}Linking $e files...${NC}"
    link_files "$BASE/custom/$e/$CONFIG"
  fi
done
