#!/usr/bin/env bash

source lib.sh

home_envs
set_trap

link_files() {
  DIR=$1
  CONFIG=$2
  MODE=$3

  if [ -z "$CONFIG" ]; then
    shopt -s nullglob
    cs=("$DIR/"*)
    shopt -u nullglob
  else
    cs=("$CONFIG")
  fi

  for c in "${cs[@]}"
  do
    c=$(basename $c)
    if [ -d "$DIR/$c" ]; then
      find "$DIR/$c" -type f -printf '%P\n' | while IFS= read -rd $'\n' file; do
        path="$DIR/$c/$file"
        dir=`dirname "$path"`

        mkdir -p "$HOME/`dirname $file`"

        if [[ -z "$MODE" ]]; then
          echo "Linking $c/$file"
          ln -sf "$path" "$HOME/$file"
        else 
          echo "Moving $c/$file"
          cp -f --preserve=mode,timestamps "$path" "$HOME/$file"
        fi
      done
    fi
  done
}

# open tomb
open_tomb

# link files
IFS=', ' read -r -a es <<< "${ENVS[$ENV]}"
for e in "${es[@]}"
do
  echo 
  echo -e "${GREEN}Linking $e files...${NC}"
  link_files "$BASE/home/$e" "$2"
  link_files "$BASE/secrets/home/$e" "$2" true
done

# close tomb
close_tomb
