#!/usr/bin/env bash

source lib.sh

set_trap

ENV=$1
KIND=$2
[[ "$KIND" != "etc" ]] && [[ "$KIND" != "home" ]] && [[ "$KIND" != "var" ]] && echo "Invalid kind $KIND [etc|home|var]" && exit 1

# open tomb
open_tomb

# list secrets
echo
echo -e "${GREEN}Listing secrets in $KIND/$ENV...${NC}"
find "$BASE/secrets/$KIND/$ENV" -type f -printf '%P\n'

# close tomb
close_tomb
