#!/usr/bin/env bash

source lib.sh

set_trap

ENV=$1
FILE=$2
[[ ! -f "$FILE" ]] && echo "File $FILE does not exists" && exit 1

if [[ "$FILE" == "/etc/"* ]]; then
  ROOT="etc/$ENV"
  PREFIX="/etc/"
elif [[ "$FILE" == "$HOME/"* ]]; then
  ROOT="home/$ENV/$3"
  PREFIX="$HOME/"
elif [[ "$FILE" == "/var/"* ]]; then
  ROOT="var/$ENV"
  PREFIX="/var/"
else
  echo 'Invalid secret type'
  exit 1
fi
TARGET=${FILE#"$PREFIX"}

# open tomb
open_tomb

# put secret
TARGET_FILE="$BASE/secrets/$ROOT/$TARGET" 
if [[ -f "$TARGET_FILE" ]]; then
  echo
  echo -e "${GREEN}Replacing file $ROOT/$TARGET${NC}"
  cp -f "$FILE" "$TARGET_FILE"
else
  echo
  echo -e "${GREEN}Putting file $ROOT/$TARGET${NC}"
  read -p "Are you sure? " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    mkdir -p `dirname "$TARGET_FILE"`
    cp "$FILE" "$TARGET_FILE"
  fi
fi

# close tomb
close_tomb