#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo 'No environment provided'
    exit 1
fi

declare -A ENVS
ENVS[kjanosz.com]="nixos kjanosz.com"
ENVS[laptop]="nixos laptop"

BASE=`dirname "$(readlink -f "$0")"`
ENV=$1

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

trap '
  trap - INT # restore default INT handler
  kill -s INT "$$"
' INT

sync_files() {
  find "$1" -type f -printf '%P\n' | while IFS= read -rd $'\n' file; do
    path="$1/$file"
    dir=`dirname "$path"`
    base="$2"

    sudo mkdir -p "/$base/`dirname $file`"
    if [ ${file: -4} == ".gpg" ]; then # treat it as an encrypted file
      file_dir=`dirname "$file"`
      file_name=`basename "$file" .gpg`
      echo "Decrypting $file"
      gpg --no-verbose --quiet --batch --yes --decrypt "$path" | \
        sudo tee "/$base/$file_dir/$file_name" > /dev/null | \
        sudo chmod --reference="$path" "/$base/$file_dir/$file_name" | \
        sudo chown --reference="/$base/$file_dir" "/$base/$file_dir/$file_name"
    else
      echo "Moving $file"
      sudo cp -f --preserve=mode,timestamps "$path" "/$base/$file"
    fi
  done
}

# sync files
IFS=', ' read -r -a es <<< "${ENVS[$ENV]}"
for e in "${es[@]}"
do
  if [ -d "$BASE/etc/$e" ]; then
    echo 
    echo -e "${GREEN}Syncing $e files in etc...${NC}"
    sync_files "$BASE/etc/$e" "etc"
  fi

  if [ -d "$BASE/var/$e" ]; then
    echo 
    echo -e "${GREEN}Syncing $e files in var...${NC}"
    sync_files "$BASE/var/$e" "var"
  fi
done
