addSbtPlugin("io.get-coursier"  % "sbt-coursier"         % "1.0.0-RC12")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("org.ensime"       % "sbt-ensime"           % "1.12.13")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"              % "1.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.3.2")
